### ISSUE TITLE
Organization Visualization

### ISSUE THREAD

**Issue by arthursoares** [envisioning/godzilla#87]
This will feature a new visualization mode for Godzilla where Organizations (companies / startups) will be listed around the map (as technologies are listed) and technologies will be only listed as nodes.

When you click or hover an organization, it will show the related technologies inside the map.

# Voting

- Should we add support for Organization collections? This will reflect on TDB.

**Comment by thomazrezende** [comment]
YES. I believe we should at least set the structure for this info on TDB. Some clients might want this kind of info on the map (as Proximus did) and this extra ring of elements isn't that hard to create on the map.

**Comment by michellzappa** [comment]
+1 for outside ring with Organizations. Will sketch something for us.

**Comment by NDuma** [comment]
Yes, agreed on Organizations. Crunchbase has an open initiative for data; Angel.co has an API framework - If the user logs in with their OAuth we could use their Calls to generate data.

**Comment by michellzappa** [comment]
Open Data is coming 2017 ;-)

**Comment by NDuma** [comment]
This seems to be pretty comprehensive beginning on locating research:
[GRID - Global Research Identifier Database](https://grid.ac/downloads)
[NSF - Example](https://grid.ac/institutes/grid.431093.c)

**Comment by arthursoares** [comment]
Coolio. This is definitely going to backlog and https://github.com/envisioning/techdb
