### ISSUE TITLE
Standardize naming

### ISSUE THREAD

**Issue by michellzappa** [envisioning/godzilla#90]
- Standardize naming of Tool / Project
- Tools is referred to as "Godzilla" or "Visualization Tool"
- I vote on sticking to Godzilla for Repo + Domain (both are currently "readiness.io")
- We can still refer to the tool as "Envisioning visualization tool" or something, but all project & code related names become Godzilla.

Thoughts?

Ping @arthursoares  @thomazrezende

**Comment by arthursoares** [comment]
IMHO, `godzilla` is our internal project code. 
This should be upgraded to Envisioning's visualization tool. 

I plan on fixing this with #100
