### ISSUE TITLE
Right Side Bar Scroll / Zoom Samsung Galaxy S5

### ISSUE THREAD

**Issue by NDuma** [envisioning/godzilla#93]
Issue & UI Enhancement : Mobile

Chrome emulator did not replicate issue experienced on mobile device. The width was much wider & more viewable, the screenshot contains a box depicting roughly the viewing area experienced.

Recommend enlarging scaling of navigation buttons on mobile screens. Tied to issue #92

Description also in screenshot

![screenshot_3](https://cloud.githubusercontent.com/assets/8163869/12535427/db77ae0e-c237-11e5-89c2-eb67987e9748.png)

**Comment by michellzappa** [comment]
Thanks — we’re reviewing the architecture of Godzilla to facilitate mobile
navigation!

**Comment by NDuma** [comment]
I'm glad it's relevant :+1: 

Forgot to mention the main issue with the scroll bar was an issue scrolling.
Touch seemed to move the background and not the text; tried using finger on scroll ui and it was very narrow creating creating unintended actions.

**Comment by michellzappa** [comment]
Interface is definitely not mobile friendly yet. Will be fixed at some
point.
