### ISSUE TITLE
Portfolio Creation & Show Distribution

### ISSUE THREAD

**Issue by NDuma** [envisioning/godzilla#96]
Feature:

Allow users to create portfolios of technologies; add from #95.

Show distribution of Selection on Readiness scale
BarChart attached.

Consideration for equities chart styles for historical references over time mentioned at bottom.

![screenshot_9](https://cloud.githubusercontent.com/assets/8163869/12535665/600e8d66-c23f-11e5-9abb-b56fb9c72e36.png)

**Comment by NDuma** [comment]
Portfolio links to https://github.com/envisioning/techdb/issues/13 "Collection"

**Comment by michellzappa** [comment]
Good one for the future.
Mirrors Airbnb’s Price Range tool in sidebar.
